### ISSUE TITLE
The "back" transition flickers

### ISSUE THREAD

**Issue by wcandillon** [IjzerenHein/react-navigation-shared-element#21]
I built a small shared transition that work great on the way in but flickers on the way back. I have able to reproduce it on the https://github.com/IjzerenHein/react-navigation-shared-element-demo example.

See screen recording below.

https://streamable.com/4amtb

**Comment by wcandillon** [comment]
Here is the issue with the transition that I'm trying to build: https://streamable.com/3iu5y

Should I try with `react-native-shared-element` directly? In `react-native-shared-element`, there is the possibility to register the parent component. Could that help potentially?

Thank you for making shared transitions in React Native a reality.

**Comment by IjzerenHein** [comment]
Hey! Hmm, nore sure what's going on here. It might be related to the border-radius. Could you do me a favour, and change the border-radius in the main-screen to 0, and see whether the problem persists?

**Comment by sa8ab** [comment]
Man, @wcandillon , I like your work on youtube but actually can not understand what you do there, lol !!
It will be a great help teaching the basics for free 😄😄

**Comment by wcandillon** [comment]
@IjzerenHein I definitely think that it's related to the border radius. What about the ancestor node in `react-native-shared-element`, what is it useful for?

@sa8ab What do you mean exactly?

**Comment by IjzerenHein** [comment]
> @IjzerenHein I definitely think that it's related to the border radius.

How so @wcandillon, is the problem gone when border-radius on the first screen is 0? I suspect this has to do with the Android Fresco library and the way it handles scale-type transforms. I've seen problems with this before. It's better if you open an issue in the `react-native-shared-element` lib with a gif/video demonstrating the problem.

>  What about the ancestor node in react-native-shared-element, what is it useful for?

The ancestor is needed to correctly calculate the position of the element on the screen. This is because the screen you are transitioning to can be translated (e.g. 200px to the right of the screen, when performing a horizontal stack animation). In such a case, obtaining the absolute position will return coordinates outside the screen. The ancestor node is then uses to correct for this offset.

**Comment by IjzerenHein** [comment]
@wcandillon is still this a problem, or can I close this?

**Comment by wcandillon** [comment]
Please close this for now. But I do plan to come back to this example
again. Maybe when SDK 37 is released or before depending.

**Comment by IjzerenHein** [comment]
> Maybe when SDK 37 is released or before depending. 

Sounds good 👍

**Comment by IjzerenHein** [comment]
Oh yeah, I've been so free to reference your Airbnb video in the readme:
https://github.com/IjzerenHein/react-navigation-shared-element#videos

Let me know in case you'd rather not have that or if you would like me to include your name.

Love the video btw ❤️
