### ISSUE TITLE
Shared element missed id when goes back

### ISSUE THREAD

**Issue by teradeiriz** [IjzerenHein/react-navigation-shared-element#50]
Cloned example project with images from Unsplash. I add swiping feature for swiping images. As you can see from the gif below shared animation saves first initial id as shared id and animation doesn't work when user goes back. Do you have any ideas how it can be fixed?

Let me know if I did smth wrong, I adjust code from example.

```
    "@react-navigation/native": "^5.0.6",
    "@react-navigation/stack": "^5.0.6",
    "react-native-shared-element": "^0.5.6",
    "react-native-swiper": "^1.6.0-nightly.5",
    "react-navigation-shared-element": "^5.0.0-alpha1"
```

![1234567](https://user-images.githubusercontent.com/60436907/78129887-f667e180-7420-11ea-86db-36b20d9d7427.gif)

**Comment by TnRc** [comment]
Using an older version of react-navigation (4.0.0 for example) solved this issue for me on Android.

**Comment by IjzerenHein** [comment]
Can you share an expo/snack that demonstrates the problem?

**Comment by IjzerenHein** [comment]
Or even better, a test-case in the `./example` test-app 👍

**Comment by tedcurrent** [comment]
I struggled with this a lot and even copy pasted the code directly from the example and still failed. However, I grabbed the dependency directly from Github instead of npm and it works. So i guess this has been fixed at some point. This is not good for production code, but try this:
`"react-navigation-shared-element": "git+https://github.com/IjzerenHein/react-navigation-shared-element#master"`

**Comment by IjzerenHein** [comment]
I'm going to close this issue. Feel free to reopen with a PR adding a test-case to the `example` app, demonstrating this problem 👍
