### ISSUE TITLE
Rendering elements on top of animation

### ISSUE THREAD

**Issue by thijs-qv** [IjzerenHein/react-navigation-shared-element#51]
I have a transition between a list and a detail screen. On the detail screen, I overlay two elements over an image. The transition of the image works fine, but the animation renders on top of the overlaying elements. Once the animation finishes, the elements are rendered on top of the image. Is there any way to have these elements displayed over the animation while it runs?

**Comment by thijs-qv** [comment]
Looks like the transition image has absolute positioning (which makes sense, as it should display over all other elements). I wrapped the overlaying elements in SharedElements (and created "dummies" for them in the list view as they didn't exist there). This seems to be most logical way of going about this.

**Comment by IjzerenHein** [comment]
Hi! The absolute positioning on top of the screen is by design and is something you need to take into account. Fortunately there are ways to address this problem. 

What you can do is to wrap the overlayed elements in the Detail screen also in a `<SharedElement>`. When you now return the ids of those elements in your `sharedElements` function (the order of the array also determines the z-order), it will cause those elements to be drawn in front of the element that you are transitioning. Additionally you can use a fade-in effect to make that element appear in a smooth manner.

Here's an example:

**Screen 1**

```
<SharedElement id='myelement'>...</SharedElement>
```

**Screen 2**

```
<View>
  <SharedElement id='myelement'>...</SharedElement>
  <SharedElement id='overlay1'>...</SharedElement>
  <SharedElement id='overlay2'>...</SharedElement>
</View>

static sharedElements = () => {
  return [
    {id: 'myelement'},
    {id: 'overlay1', animation: 'fade-in'},
    {id: 'overlay2', animation: 'fade-in'},
  ];
};
```

**Comment by thijs-qv** [comment]
Awesome! Thanks for your reply. I'm still having some issues, but I think it's because of the way I built up the screen, I guess I'll have to rewrite some things. (I have an overlay that is on the top of the screen, absolute positioned, but I'm rendering it last so it can actually overlap the other elements.)

**Comment by thijs-qv** [comment]
I actually do have a follow up question/issue related to this: I'm trying to achieve this effect for the header of the screen (the header is partly transparent and has a negative bottomMargin equal to its height so it overlays the screen contents). However adding a sharedElement around the header component breaks the sharedElement transitions. I am using the v5-alpha branch by the way. Is this (the way of overlaying on animations) going to support header components in react-navigation-v5?

**Comment by youssef212** [comment]
there is a lot of problems with v5 and v4 for me this is one of them at least in v4 and i am not sure about the tab bar problems as well so is this still maintained ?
